const num = (d) => (d === null || d === undefined ? null : Number(d));

export const publicUser = (u) => ({
  id: u.id,
  name: u.name,
  email: u.email,
  role: u.role,
  isActive: u.isActive,
  createdAt: u.createdAt,
});

export const serializeCategory = (c) => ({
  id: c.id,
  name: c.name,
  slug: c.slug,
  icon: c.icon,
  sortOrder: c.sortOrder,
  parentId: c.parentId,
  productCount: c._count?.products,
});

export const serializeProduct = (p) => ({
  id: p.id,
  code: p.code,
  barcode: p.barcode,
  name: p.name,
  description: p.description,
  categoryId: p.categoryId,
  categoryName: p.category?.name,
  price: num(p.price),
  unit: p.unit,
  soldByWeight: p.soldByWeight,
  stock: num(p.stock),
  lowStockThreshold: num(p.lowStockThreshold),
  discountPercent: num(p.discountPercent),
  isQuickKey: p.isQuickKey,
  imageUrl: p.imageUrl,
  isActive: p.isActive,
  updatedAt: p.updatedAt,
});

export const serializeSettings = (s) => ({
  storeName: s.storeName,
  tagline: s.tagline,
  gstin: s.gstin,
  address: s.address,
  phone: s.phone,
  upiVpa: s.upiVpa,
  upiPayeeName: s.upiPayeeName,
  currency: s.currency,
  taxRate: num(s.taxRate),
  maxCashierDiscountPct: num(s.maxCashierDiscountPct),
  receiptFooter: s.receiptFooter,
  updatedAt: s.updatedAt,
});

export const serializeTransaction = (t) => ({
  id: t.id,
  clientId: t.clientId,
  invoiceNo: t.invoiceNo,
  terminalId: t.terminalId,
  cashier: t.cashier ? { id: t.cashier.id, name: t.cashier.name } : undefined,
  status: t.status,
  paymentMethod: t.paymentMethod,
  customerPhone: t.customerPhone,
  subtotal: num(t.subtotal),
  itemDiscount: num(t.itemDiscount),
  billDiscount: num(t.billDiscount),
  discountReason: t.discountReason,
  taxRate: num(t.taxRate),
  taxableAmount: num(t.taxableAmount),
  taxTotal: num(t.taxTotal),
  grandTotal: num(t.grandTotal),
  amountTendered: num(t.amountTendered),
  changeDue: num(t.changeDue),
  wasOffline: t.wasOffline,
  soldAt: t.soldAt,
  syncedAt: t.syncedAt,
  voidedAt: t.voidedAt,
  voidReason: t.voidReason,
  itemCount: t._count?.items ?? t.items?.length,
  items: t.items?.map((i) => ({
    id: i.id,
    productId: i.productId,
    productName: i.productName,
    productCode: i.productCode,
    unit: i.unit,
    soldByWeight: i.soldByWeight,
    quantity: num(i.quantity),
    unitPrice: num(i.unitPrice),
    discountPercent: num(i.discountPercent),
    lineSubtotal: num(i.lineSubtotal),
    lineDiscount: num(i.lineDiscount),
    billDiscountShare: num(i.billDiscountShare),
    netAmount: num(i.netAmount),
  })),
});
